// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {

    // ==== MOTOR CONTROLLERS ====
    // This is where you should put your motor controllers and have them associated
    // with the correct CAN ID on the bus.
    public static final class DriveConstants {
        public static final int kLeftFrontMotorCanID = 0;
        public static final int kRightFrontMotorCanID = 1;
        public static final int kLeftRearMotorCanID = 2;
        public static final int kRightRearMotorCanID = 3;
    }

    // ==== POWER LIMITS ====
    // This is where you should put power limits for each subsystem that has power.
    // Be careful with power limits, this can cause bad things to happen if you give
    // the subsystem more than enough power.
    public static final class PowerConstants {
        public static final double drivePowerLimit = 1.0;
        public static final double shooterPowerLimit = 1.0;
    }

    // ==== CONTROLLER PORTS ====
    // This is where you should put your controller ports for the robot. This is vital
    // as the ports have to be in this order for things to work properly.
    public static final class ControllerConstants {
        public static final int driverJoystickPort = 0;
        public static final int auxXboxController = 1;
    }
}
