// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import frc.robot.commands.*;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj.motorcontrol.PWMVictorSPX;

public class BallIngest extends SubsystemBase {
    private PWMVictorSPX ingestVictor;

    public BallIngest() {
        ingestVictor = new PWMVictorSPX(1);
        addChild("IngestVictor", ingestVictor);
        ingestVictor.setInverted(false);
    }

    @Override
    public void periodic() {

    }

    @Override
    public void simulationPeriodic() {
    }
}
