// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import frc.robot.Constants;
import frc.robot.commands.*;
import edu.wpi.first.util.sendable.Sendable;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import com.ctre.phoenix.motorcontrol.can.VictorSPX;

public class BallIngest extends SubsystemBase {
    private VictorSPX ingestVictor;

    public BallIngest() {
        ingestVictor = new VictorSPX(Constants.ShooterConstants.kIntakeMotorCanID);
        addChild("IngestVictor", (Sendable) ingestVictor);
        ingestVictor.setInverted(false);
    }

    @Override
    public void periodic() {

    }

    @Override
    public void simulationPeriodic() {
    }
}
