// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;

import frc.robot.Constants;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj.Encoder.IndexingType;
import edu.wpi.first.wpilibj.Encoder;
import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;
public class BallShooter extends SubsystemBase {

    private CANSparkMax shooterSparkMAX;
    private Encoder shooterEncoder;

    public BallShooter() {
        shooterSparkMAX = new CANSparkMax(Constants.ShooterMotorConstants.kShooterMotorCanID, MotorType.kBrushed);
        shooterSparkMAX.setInverted(false);

        shooterEncoder = new Encoder(14, 15, false);
        addChild("ShooterEncoder", shooterEncoder);
        shooterEncoder.setDistancePerPulse(1.0);
        shooterEncoder.setIndexSource(16, IndexingType.kResetOnRisingEdge);
    }

    @Override
    public void periodic() {

    }

    @Override
    public void simulationPeriodic() {

    }
}
